function s = parameter_ellipse(I,threshold)

bw = ~(I < threshold);
L = bwlabel(bw);
stats = regionprops(L,'Area');
maxid = find([stats.Area] == max([stats.Area]));
bw = ismember(L,maxid);
s = regionprops(bw,{...
    'Area',...
    'Centroid',...
    'MajorAxisLength',...
    'MinorAxisLength',...
    'Orientation'});